### ISSUE TITLE
Preserve logging color

### ISSUE THREAD

**Issue by RochesterinNYC** [pivotal-cf-experimental/concourse-filter#1]
It'd be great to preserve color in the output logs.

Before using the filter:
![screen shot 2016-07-01 at 6 40 49 pm](https://cloud.githubusercontent.com/assets/1504464/16536064/5b65cd66-3fbb-11e6-9254-ae920d5faa0a.png)

With using the filter:
![screen shot 2016-07-01 at 6 40 22 pm](https://cloud.githubusercontent.com/assets/1504464/16536060/4c017b4a-3fbb-11e6-9e0d-88c273d95b1c.png)

**Comment by sesmith177** [comment]
We created a chore in the icebox: https://www.pivotaltracker.com/story/show/133046105

**Comment by jchesterpivotal** [comment]
Turns out this was not due to concourse-filter. Instead, our RSpec suites weren't emitting colours on CI.
